[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 10
offset = { x = 0, y = 0 }
builtin_box_drawing = false

[colors.primary]
background = "#101010"
foreground = "#F4F4F4"
dim_foreground = "#CACACA"
bright_foreground = "#FFFFFF"

[colors.cursor]
text = "#F4F4F4"
cursor = "#CACACA"

[colors.vi_mode_cursor]
text = "#F4F4F4"
cursor = "#875fff"

[colors.search.matches]
foreground = "#F4F4F4"
background = "#666666"

[colors.search.focused_match]
foreground = "#F4F4F4"
background = "#6050DC"

[colors.footer_bar]
foreground = "#F4F4F4"
background = "#292929"

[colors.hints.start]
foreground = "#F4F4F4"
background = "#6050DC"

[colors.hints.end]
foreground = "#F4F4F4"
background = "#424242"

[colors.selection]
text = "#F4F4F4"
background = "#292929"

[colors.normal]
black = "#292929"
red = "#FF5577"
green = "#90EE90"
yellow = "#FFDD60"
blue = "#6050DC"
magenta = "#875FFF"
cyan = "#799FB6"
white = "#E0E0E0"

[colors.bright]
black = "#666666"
red = "#FF9CB0"
green = "#BCF5BC"
yellow = "#FFE18C"
blue = "#958AE8"
magenta = "#B79FFF"
cyan = "#AFC5D3"
white = "#FFFFFF"

[colors.dim]
black = "#000000"
red = "#993347"
green = "#568F56"
yellow = "#99853A"
blue = "#30286E"
magenta = "#513999"
cyan = "#495F6D"
white = "#ABABAB"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Off" }
vi_mode_style = { shape = "Block", blinking = "Off" }
unfocused_hollow = false


